package com.synapse.computationengine.model;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Represents a BUY or SELL signal generated by the engine.
 */
public record TradingSignal(
    String symbol,
    String signalType, // "BUY" or "SELL"
    BigDecimal triggerPrice,
    BigDecimal movingAverage,
    Instant timestamp
) {}